import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'

export default function Home() {
  useEffect(() => {
    window.location.href = 'https://doc.tigerzh.com'
  }, [])

  return (
    <>
      <Head>
        <title>Next app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        hello tigerzh
      </main>
    </>
  )
}
